{% set name = "redo" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52a14200004d6708924a547b31b7d1c717cb36b944f3a5c7b176e0d61ab81eef


build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - retry = redo.cmd:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  imports:
    - redo
  commands:
    - pip check

about:
  home: https://github.com/mozilla-releng/redo
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: 'Utilities to retry Python callables.'

  description: |
    Redo provides various means to add seamless ability to retry to any Python callable.
    Redo includes a plain function (redo.retry), a decorator (redo.retriable), and a
    context manager (redo.retrying) to enable you to integrate it in the best possible
    way for your project. As a bonus, a standalone interface is also included ("retry").
  doc_url: https://github.com/mozilla-releng/redo
  dev_url: https://github.com/mozilla-releng/redo

extra:
  recipe-maintainers:
    - jaimergp
    - mozbhearsum
